project_name: arrans_overlay_workflow_builder
builds:
  -
    id: "overlay_workflow_builder_generator"
    binary: "overlay_workflow_builder_generator"
    dir: cmd/generate
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
archives:
  -
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  -
    vendor: Ubels Software Development
    homepage: https://github.com/arran4/
    maintainer: Arran Ubels <arran@ubels.com.au>
    description: NA
    license: Private
    formats:
        - apk
        - deb
        - rpm
        - termux.deb
        - archlinux
    release: 1
    section: default
    priority: extra
